openapi: 3.1.0
info:
  title: Ingenium VenueServer
  description: RESTful API of Ingenium VenueServer that interfaces with test venues
  version: 14.1-TP
paths:
  /api/v3/health:
    get:
      tags:
      - HEALTH
      summary: Check health status of VenueServer
      operationId: health_api_v3_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v3/mtak/start:
    post:
      tags:
      - MTAK
      summary: Start MTAK on the venue GDS host for the specified AMPCS session ids
      operationId: start_mtak_api_v3_mtak_start_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MtakStartBodyModel'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MtakStartResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v3/mtak/shutdown:
    post:
      tags:
      - MTAK
      summary: Shutdown MTAK that was started by VenueServer
      operationId: shutdown_mtak_api_v3_mtak_shutdown_post
      responses:
        '204':
          description: Successful Response
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v3/cmd/fsw_cmd:
    post:
      tags:
      - COMMAND
      summary: Send a FSW command via MTAK
      operationId: fsw_cmd_api_v3_cmd_fsw_cmd_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FswCmdBodyModel'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CmdDispatchedResp'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v3/cmd/hw_cmd:
    post:
      tags:
      - COMMAND
      summary: Send a HW command via MTAK
      operationId: hw_cmd_api_v3_cmd_hw_cmd_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HwCmdBodyModel'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CmdDispatchedResp'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v3/cmd/sse:
    post:
      tags:
      - COMMAND
      summary: Send a SSE command via MTAK
      description: Send a SSE (Simulation and Support Equipment) command via MTAK
      operationId: sse_cmd_api_v3_cmd_sse_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SseCmdBodyModel'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CmdDispatchedResp'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v3/cmd/binary_file:
    post:
      tags:
      - COMMAND
      summary: Upload a file to flight computer via MTAK
      operationId: binary_file_api_v3_cmd_binary_file_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BinaryFileBodyModel'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CmdDispatchedResp'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v3/cmd/scmf:
    post:
      tags:
      - COMMAND
      summary: Upload a SCMF file to flight
      operationId: scmf_file_api_v3_cmd_scmf_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScmfFileBodyModel'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CmdDispatchedResp'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    BinaryFileBodyModel:
      properties:
        sessionId:
          type: integer
          title: Sessionid
          description: The AMPCS session to send the command through
        sourceFilePath:
          type: string
          title: Sourcefilepath
          description: 'The full path on GDS host (ex: /proj/europa/sit/current/files/myfile.data)'
        targetFilePath:
          type: string
          title: Targetfilepath
          description: The full onboard path (i.e. /eng1/myfile.data
        overwrite:
          type: boolean
          title: Overwrite
          description: if True will overwrite any existing onboard file
          default: true
        fileType:
          type: integer
          title: Filetype
          description: The file type that should be used to build the binary file
            into a SCMF
        stringSelection:
          allOf:
          - $ref: '#/components/schemas/StringSelection'
          description: Specifies the MTAK string to send the command
          default: DEFAULT
        timeout:
          type: integer
          minimum: 0.0
          title: Timeout
          description: The timeout on the dispatch process in seconds
          default: 10
      type: object
      required:
      - sessionId
      - sourceFilePath
      - targetFilePath
      - fileType
      title: BinaryFileBodyModel
    CmdDispatchedResp:
      properties:
        cmdRequested:
          type: string
          title: Cmdrequested
          description: This mirrors what was received as the requested command string
          default: ''
        dispatchTime:
          type: string
          title: Dispatchtime
          description: 'Time that the dispatch occurred. Example: 2017-09-25T03:57:42.676Z'
          default: ''
      type: object
      title: CmdDispatchedResp
    DefaultCmdString:
      type: string
      enum:
      - A
      - B
      - AB
      title: DefaultCmdString
      description: An enumeration.
    ErrorResponse:
      properties:
        message:
          type: string
          title: Message
          description: Error message
          default: ''
      type: object
      title: ErrorResponse
    FswCmdBodyModel:
      properties:
        sessionId:
          type: integer
          title: Sessionid
          description: The AMPCS session to send the command through
        commandString:
          type: string
          title: Commandstring
          description: The command string including the command stem and any arguments
        validate:
          type: boolean
          title: Validate
          description: Flag for AMPCS to validate the command against the FSW dict
            before radiating
          default: true
        stringSelection:
          allOf:
          - $ref: '#/components/schemas/StringSelection'
          description: Which sides of flight computer the command is for
          default: DEFAULT
        timeout:
          type: integer
          minimum: 0.0
          title: Timeout
          description: The timeout on the dispatch process in seconds
          default: 10
      type: object
      required:
      - sessionId
      - commandString
      title: FswCmdBodyModel
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    HealthStatus:
      properties:
        status:
          allOf:
          - $ref: '#/components/schemas/HealthStatusEnum'
          description: health status
        message:
          type: string
          title: Message
          description: status message
      type: object
      required:
      - status
      - message
      title: HealthStatus
    HealthStatusEnum:
      type: string
      enum:
      - OK
      - ERROR
      - UNKNOWN
      title: HealthStatusEnum
      description: An enumeration.
    HwCmdBodyModel:
      properties:
        sessionId:
          type: integer
          title: Sessionid
          description: The AMPCS session to send this file through
        commandStem:
          type: string
          title: Commandstem
          description: The command stem of the HW Command
        stringSelection:
          allOf:
          - $ref: '#/components/schemas/StringSelection'
          description: Specifies the MTAK string to send the command
          default: DEFAULT
        timeout:
          type: integer
          minimum: 0.0
          title: Timeout
          description: The timeout on the dispatch process in seconds
          default: 10
      type: object
      required:
      - sessionId
      - commandStem
      title: HwCmdBodyModel
    MtakStartBodyModel:
      properties:
        sessionIds:
          items:
            type: integer
          type: array
          title: Sessionids
          description: AMPCS session ids to start MTAK on
        timeout:
          type: integer
          minimum: 25.0
          title: Timeout
          description: How long to wait until timeout in seconds. The minimum is 25
            seconds since MTAK takes some time to start
          default: 30
        defaultCmdString:
          allOf:
          - $ref: '#/components/schemas/DefaultCmdString'
          description: Which sides of flight computer the command is for. This will
            be used if default is used for stringSelection.
          default: AB
      type: object
      required:
      - sessionIds
      title: MtakStartBodyModel
    MtakStartResponse:
      properties:
        sessionIds:
          items:
            type: integer
          type: array
          title: Sessionids
          description: AMPCS session ids
        startTime:
          type: string
          title: Starttime
          description: Time that MTAK started
      type: object
      required:
      - sessionIds
      - startTime
      title: MtakStartResponse
    ScmfFileBodyModel:
      properties:
        sessionId:
          type: integer
          title: Sessionid
          description: The AMPCS session to send the command through
        filePath:
          type: string
          title: Filepath
          description: 'The full path on GDS host (ex: /proj/europa/sit/current/files/myfile.scmf)'
        disableChecks:
          type: boolean
          title: Disablechecks
          description: Disables the check done by AMPCS for invalid scmf file
          default: false
        timeout:
          type: integer
          minimum: 0.0
          title: Timeout
          description: The timeout on the dispatch process in seconds
          default: 10
      type: object
      required:
      - sessionId
      - filePath
      title: ScmfFileBodyModel
    SseCmdBodyModel:
      properties:
        sessionId:
          type: integer
          title: Sessionid
          description: The AMPCS session to send the command through
        commandString:
          type: string
          title: Commandstring
          description: The command string including the command stem and any arguments
        timeout:
          type: integer
          minimum: 0.0
          title: Timeout
          description: The timeout on the dispatch process in seconds
          default: 10
      type: object
      required:
      - sessionId
      - commandString
      title: SseCmdBodyModel
    StringSelection:
      type: string
      enum:
      - DEFAULT
      - A
      - B
      - AB
      title: StringSelection
      description: An enumeration.
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
tags:
- name: MTAK
  description: Start or stop MTAK sessions
- name: COMMAND
  description: Send commands
- name: HEALTH
  description: Check service health
